/*
 * GmodStore
 * Welcome to the Gmodstore API! You can use our API to access Gmodstore API endpoints, which can be used interact with Gmodstore programmatically.
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package no.everyday.gmodstore_sdk.api;

import no.everyday.gmodstore_sdk.ApiException;
import no.everyday.gmodstore_sdk.model.AddonListResponse;
import no.everyday.gmodstore_sdk.model.AddonResponse;
import no.everyday.gmodstore_sdk.model.ErrorResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AddonsApi
 */
@Ignore
public class AddonsApiTest {

    private final AddonsApi api = new AddonsApi();

    /**
     * Fetch a single addon
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAddonTest() throws ApiException {
        Long addonId = null;
        List<String> with = null;
        AddonResponse response = api.getAddon(addonId, with);

        // TODO: test validations
    }
    /**
     * Fetch all the addons that you have access to
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listSelfAddonsTest() throws ApiException {
        List<String> with = null;
        AddonListResponse response = api.listSelfAddons(with);

        // TODO: test validations
    }
}
