/*
 * GmodStore
 * Welcome to the Gmodstore API! You can use our API to access Gmodstore API endpoints, which can be used interact with Gmodstore programmatically.
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package no.everyday.gmodstore_sdk.api;

import no.everyday.gmodstore_sdk.ApiException;
import no.everyday.gmodstore_sdk.model.AddonReviewListResponse;
import no.everyday.gmodstore_sdk.model.AddonReviewResponse;
import no.everyday.gmodstore_sdk.model.Error;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AddonReviewsApi
 */
@Ignore
public class AddonReviewsApiTest {

    private final AddonReviewsApi api = new AddonReviewsApi();

    /**
     * Fetch a review of an addon
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAddonReviewTest() throws ApiException {
        Long addonId = null;
        Long reviewId = null;
        List<String> with = null;
        AddonReviewResponse response = api.getAddonReview(addonId, reviewId, with);

        // TODO: test validations
    }
    /**
     * Fetch all the reviews of an addon
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAddonReviewsTest() throws ApiException {
        Long addonId = null;
        List<String> with = null;
        AddonReviewListResponse response = api.listAddonReviews(addonId, with);

        // TODO: test validations
    }
}
