/*
 * gmodstore
 * Welcome to the GmodStore API! You can use our API to access GmodStore API endpoints, which can be used interact with GmodStore programmatically.  # Rate limits Every request you make to the GmodStore API will count against your rate limit, which at the time of writing this, is 60 requests / minute. An up-to-date value will always provided in the `X-RateLimit-Limit` header The number of requests you have remaining before you must wait is provided in the `X-RateLimit-Remaining` header.  # API SDKs For a list of available API SDKs check the README here: https://github.com/everyday-as/gmodstore-api-docs#client-libraries
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.everyday.gmodstore_sdk.api;

import no.everyday.gmodstore_sdk.ApiException;
import no.everyday.gmodstore_sdk.model.Error;
import no.everyday.gmodstore_sdk.model.GetProductReviewResponse;
import no.everyday.gmodstore_sdk.model.ProductReviewFilter;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProductReviewsApi
 */
@Ignore
public class ProductReviewsApiTest {

    private final ProductReviewsApi api = new ProductReviewsApi();

    
    /**
     * Show the specified review for a product
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProductReviewTest() throws ApiException {
        String product = null;
        String review = null;
        ProductReviewFilter filter = null;
                GetProductReviewResponse response = api.getProductReview(product, review, filter);
        // TODO: test validations
    }
    
    /**
     * List all reviews for a product
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listProductReviewsTest() throws ApiException {
        String product = null;
        Integer perPage = null;
        String cursor = null;
        ProductReviewFilter filter = null;
                Object response = api.listProductReviews(product, perPage, cursor, filter);
        // TODO: test validations
    }
    
}
