/*
 * GmodStore
 * Welcome to the Gmodstore API! You can use our API to access Gmodstore API endpoints, which can be used interact with Gmodstore programmatically.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.everyday.gmodstore_sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AddonImages
 */
public class AddonImagesTest {
    private final AddonImages model = new AddonImages();

    /**
     * Model tests for AddonImages
     */
    @Test
    public void testAddonImages() {
        // TODO: test AddonImages
    }

    /**
     * Test the property 'bigspot'
     */
    @Test
    public void bigspotTest() {
        // TODO: test bigspot
    }

    /**
     * Test the property 'listing'
     */
    @Test
    public void listingTest() {
        // TODO: test listing
    }

    /**
     * Test the property 'listingSmall'
     */
    @Test
    public void listingSmallTest() {
        // TODO: test listingSmall
    }

}
