/*
 * GmodStore
 * Welcome to the Gmodstore API! You can use our API to access Gmodstore API endpoints, which can be used interact with Gmodstore programmatically.
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package no.everyday.gmodstore_sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.File;
import java.io.IOException;
import no.everyday.gmodstore_sdk.model.AddonVersionReleaseType;
/**
 * NewAddonVersion
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-08-27T11:54:59.353958Z[Etc/UTC]")
public class NewAddonVersion {
  @SerializedName("name")
  private String name = null;

  @SerializedName("changelog")
  private String changelog = null;

  @SerializedName("file")
  private File file = null;

  @SerializedName("release_type")
  private AddonVersionReleaseType releaseType = null;

  public NewAddonVersion name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public NewAddonVersion changelog(String changelog) {
    this.changelog = changelog;
    return this;
  }

   /**
   * You can pass in markdown here
   * @return changelog
  **/
  @Schema(required = true, description = "You can pass in markdown here")
  public String getChangelog() {
    return changelog;
  }

  public void setChangelog(String changelog) {
    this.changelog = changelog;
  }

  public NewAddonVersion file(File file) {
    this.file = file;
    return this;
  }

   /**
   * Get file
   * @return file
  **/
  @Schema(required = true, description = "")
  public File getFile() {
    return file;
  }

  public void setFile(File file) {
    this.file = file;
  }

  public NewAddonVersion releaseType(AddonVersionReleaseType releaseType) {
    this.releaseType = releaseType;
    return this;
  }

   /**
   * Get releaseType
   * @return releaseType
  **/
  @Schema(description = "")
  public AddonVersionReleaseType getReleaseType() {
    return releaseType;
  }

  public void setReleaseType(AddonVersionReleaseType releaseType) {
    this.releaseType = releaseType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NewAddonVersion newAddonVersion = (NewAddonVersion) o;
    return Objects.equals(this.name, newAddonVersion.name) &&
        Objects.equals(this.changelog, newAddonVersion.changelog) &&
        Objects.equals(this.file, newAddonVersion.file) &&
        Objects.equals(this.releaseType, newAddonVersion.releaseType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, changelog, Objects.hashCode(file), releaseType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NewAddonVersion {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    changelog: ").append(toIndentedString(changelog)).append("\n");
    sb.append("    file: ").append(toIndentedString(file)).append("\n");
    sb.append("    releaseType: ").append(toIndentedString(releaseType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
