/*
 * GmodStore
 * Welcome to the Gmodstore API! You can use our API to access Gmodstore API endpoints, which can be used interact with Gmodstore programmatically.
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package no.everyday.gmodstore_sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import no.everyday.gmodstore_sdk.model.UserBanProperties;
import org.threeten.bp.OffsetDateTime;
/**
 * UserBan
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-08-27T11:54:59.353958Z[Etc/UTC]")
public class UserBan {
  @SerializedName("user_id")
  private Long userId = null;

  @SerializedName("reason")
  private String reason = null;

  @SerializedName("unban_reason")
  private String unbanReason = null;

  @SerializedName("properties")
  private UserBanProperties properties = null;

  @SerializedName("start")
  private OffsetDateTime start = null;

  @SerializedName("end")
  private OffsetDateTime end = null;

  public UserBan userId(Long userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @Schema(description = "")
  public Long getUserId() {
    return userId;
  }

  public void setUserId(Long userId) {
    this.userId = userId;
  }

  public UserBan reason(String reason) {
    this.reason = reason;
    return this;
  }

   /**
   * Get reason
   * @return reason
  **/
  @Schema(description = "")
  public String getReason() {
    return reason;
  }

  public void setReason(String reason) {
    this.reason = reason;
  }

  public UserBan unbanReason(String unbanReason) {
    this.unbanReason = unbanReason;
    return this;
  }

   /**
   * Get unbanReason
   * @return unbanReason
  **/
  @Schema(description = "")
  public String getUnbanReason() {
    return unbanReason;
  }

  public void setUnbanReason(String unbanReason) {
    this.unbanReason = unbanReason;
  }

  public UserBan properties(UserBanProperties properties) {
    this.properties = properties;
    return this;
  }

   /**
   * Get properties
   * @return properties
  **/
  @Schema(description = "")
  public UserBanProperties getProperties() {
    return properties;
  }

  public void setProperties(UserBanProperties properties) {
    this.properties = properties;
  }

  public UserBan start(OffsetDateTime start) {
    this.start = start;
    return this;
  }

   /**
   * Get start
   * @return start
  **/
  @Schema(description = "")
  public OffsetDateTime getStart() {
    return start;
  }

  public void setStart(OffsetDateTime start) {
    this.start = start;
  }

  public UserBan end(OffsetDateTime end) {
    this.end = end;
    return this;
  }

   /**
   * Get end
   * @return end
  **/
  @Schema(description = "")
  public OffsetDateTime getEnd() {
    return end;
  }

  public void setEnd(OffsetDateTime end) {
    this.end = end;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserBan userBan = (UserBan) o;
    return Objects.equals(this.userId, userBan.userId) &&
        Objects.equals(this.reason, userBan.reason) &&
        Objects.equals(this.unbanReason, userBan.unbanReason) &&
        Objects.equals(this.properties, userBan.properties) &&
        Objects.equals(this.start, userBan.start) &&
        Objects.equals(this.end, userBan.end);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, reason, unbanReason, properties, start, end);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserBan {\n");
    
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    unbanReason: ").append(toIndentedString(unbanReason)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    end: ").append(toIndentedString(end)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
