openapi: 3.0.2
info:
  description: |-
    Welcome to the GmodStore API! You can use our API to access GmodStore API endpoints, which can be used interact with GmodStore programmatically.

    # Rate limits
    Every request you make to the GmodStore API will count against your rate limit, which at the time of writing this, is 60 requests / minute.
    An up-to-date value will always provided in the `X-RateLimit-Limit` header
    The number of requests you have remaining before you must wait is provided in the `X-RateLimit-Remaining` header.

    # API SDKs
    For a list of available API SDKs check the README here: https://github.com/everyday-as/gmodstore-api-docs#client-libraries
  title: gmodstore
  version: 3.0.0
  x-logo:
    url: https://media.gmodstore.com/_/assets/img/gmodstore/logo.svg
    backgroundColor: '#3097d1'
    href: https://www.gmodstore.com
servers:
- description: The main GmodStore API endpoint
  url: https://www.gmodstore.com
security:
- PersonalAccessToken: []
tags:
- name: Personal Access Tokens
- name: Products
- name: Product Coupons
- name: Product Purchases
- name: Product Reviews
- name: Product Versions
- name: Permission Groups
- name: Teams
- name: Team Users
- name: Users
- name: User Badges
- name: User Bans
- name: User Product Purchases
- name: User Products
- name: User Teams
paths:
  /api/v3/me:
    get:
      operationId: getMe
      summary: Fetch the current authenticated user and their access token
      tags:
      - Users
      x-internal: true
      x-accepts: application/json
  /api/v3/me/personal-access-tokens:
    get:
      operationId: listPersonalAccessTokens
      security:
      - PersonalAccessToken:
        - personal-access-tokens:read
      summary: List all the current user's personal access tokens
      tags:
      - Personal Access Tokens
      x-internal: true
      x-accepts: application/json
    post:
      operationId: createPersonalAccessToken
      security:
      - PersonalAccessToken:
        - personal-access-tokens:write
      summary: Create a new personal access token for the current user
      tags:
      - Personal Access Tokens
      x-internal: true
      x-contentType: application/json
      x-accepts: application/json
  /api/v3/me/personal-access-tokens/{personal_access_token}:
    delete:
      operationId: deletePersonalAccessToken
      security:
      - PersonalAccessToken:
        - personal-access-tokens:write
      summary: Delete the specified personal access token
      tags:
      - Personal Access Tokens
      x-internal: true
      x-accepts: application/json
    get:
      operationId: getPersonalAccessToken
      security:
      - PersonalAccessToken:
        - personal-access-tokens:read
      summary: Get a personal access token belonging to the current user
      tags:
      - Personal Access Tokens
      x-internal: true
      x-accepts: application/json
    put:
      operationId: updatePersonalAccessToken
      security:
      - PersonalAccessToken:
        - personal-access-tokens:write
      summary: Update a personal access token
      tags:
      - Personal Access Tokens
      x-internal: true
      x-accepts: application/json
  /api/v3/permission-groups:
    get:
      operationId: listPermissionGroups
      security:
      - PersonalAccessToken:
        - permission-groups:read
      summary: List all permission groups
      tags:
      - Permission Groups
      x-internal: true
      x-accepts: application/json
    post:
      operationId: createPermissionGroup
      security:
      - PersonalAccessToken:
        - permission-groups:write
      summary: Create a permission group
      tags:
      - Permission Groups
      x-internal: true
      x-contentType: application/json
      x-accepts: application/json
  /api/v3/permission-groups/{permission_group}:
    delete:
      operationId: deletePermissionGroup
      security:
      - PersonalAccessToken:
        - permission-groups:write
      summary: Delete the specified permission group
      tags:
      - Permission Groups
      x-internal: true
      x-accepts: application/json
    get:
      operationId: getPermissionGroup
      security:
      - PersonalAccessToken:
        - permission-groups:read
      summary: Show the specified permission group
      tags:
      - Permission Groups
      x-internal: true
      x-accepts: application/json
    put:
      operationId: updatePermissionGroup
      security:
      - PersonalAccessToken:
        - permission-groups:write
      summary: Update the specified permission group
      tags:
      - Permission Groups
      x-internal: true
      x-contentType: application/json
      x-accepts: application/json
  /api/v3/teams/batch:
    get:
      operationId: getTeams
      security:
      - PersonalAccessToken:
        - teams:read
      summary: Fetch a batch of teams by id
      tags:
      - Teams
      x-internal: true
      x-accepts: application/json
  /api/v3/teams:
    get:
      operationId: listTeams
      security:
      - PersonalAccessToken:
        - teams:read
      summary: List all teams
      tags:
      - Teams
      x-internal: true
      x-accepts: application/json
    post:
      operationId: createTeam
      security:
      - PersonalAccessToken:
        - teams:write
      summary: Create a new team
      tags:
      - Teams
      x-internal: true
      x-contentType: application/json
      x-accepts: application/json
  /api/v3/teams/{team}:
    delete:
      operationId: deleteTeam
      security:
      - PersonalAccessToken:
        - teams:write
      summary: Delete the specified team
      tags:
      - Teams
      x-internal: true
      x-accepts: application/json
    get:
      operationId: getTeam
      security:
      - PersonalAccessToken:
        - teams:read
      summary: Fetch the specified team
      tags:
      - Teams
      x-internal: true
      x-accepts: application/json
    put:
      operationId: updateTeam
      security:
      - PersonalAccessToken:
        - teams:write
      summary: Update the specified team
      tags:
      - Teams
      x-internal: true
      x-contentType: application/json
      x-accepts: application/json
  /api/v3/teams/{team}/users:
    get:
      operationId: listTeamUsers
      security:
      - PersonalAccessToken:
        - team-users:read
      summary: List all users in a team
      tags:
      - Team Users
      x-internal: true
      x-accepts: application/json
  /api/v3/products/batch:
    get:
      operationId: getProducts
      security:
      - PersonalAccessToken:
        - products:read
      summary: Get a batch of products by id
      tags:
      - Products
      x-internal: true
      x-accepts: application/json
  /api/v3/products/{product}/coupons:
    get:
      operationId: listProductCoupons
      security:
      - PersonalAccessToken:
        - product-coupons:read
      summary: List all coupons for a product
      tags:
      - Product Coupons
      x-internal: true
      x-accepts: application/json
    post:
      operationId: createProductCoupon
      security:
      - PersonalAccessToken:
        - product-coupons:write
      summary: Create a coupon for a product
      tags:
      - Product Coupons
      x-internal: true
      x-contentType: application/json
      x-accepts: application/json
  /api/v3/products/{product}/coupons/{coupon}:
    delete:
      operationId: deleteProductCoupon
      security:
      - PersonalAccessToken:
        - product-coupons:write
      summary: Delete the specified coupon for a product
      tags:
      - Product Coupons
      x-internal: true
      x-accepts: application/json
    get:
      operationId: getProductCoupon
      security:
      - PersonalAccessToken:
        - product-coupons:read
      summary: Show the specified coupon for a product
      tags:
      - Product Coupons
      x-internal: true
      x-accepts: application/json
    put:
      operationId: updateProductCoupon
      security:
      - PersonalAccessToken:
        - product-coupons:write
      summary: Update the specified coupon for a product
      tags:
      - Product Coupons
      x-internal: true
      x-contentType: application/json
      x-accepts: application/json
  /api/v3/products/{product}/purchases:
    get:
      operationId: listProductPurchases
      security:
      - PersonalAccessToken:
        - product-purchases:read
      summary: List all purchases for a product
      tags:
      - Product Purchases
      x-internal: true
      x-accepts: application/json
    post:
      operationId: createProductPurchase
      security:
      - PersonalAccessToken:
        - product-purchases:write
      summary: Create a purchase for a product
      tags:
      - Product Purchases
      x-internal: true
      x-contentType: application/json
      x-accepts: application/json
  /api/v3/products/{product}/purchases/{purchase}:
    get:
      operationId: getProductPurchase
      security:
      - PersonalAccessToken:
        - product-purchases:read
      summary: Show the specified purchase for a product
      tags:
      - Product Purchases
      x-internal: true
      x-accepts: application/json
    put:
      operationId: updateProductPurchase
      security:
      - PersonalAccessToken:
        - product-purchases:write
      summary: Update the specified purchase for a product
      tags:
      - Product Purchases
      x-internal: true
      x-contentType: application/json
      x-accepts: application/json
  /api/v3/products/{product}/reviews:
    get:
      operationId: listProductReviews
      security:
      - PersonalAccessToken:
        - product-reviews:read
      summary: List all reviews for a product
      tags:
      - Product Reviews
      x-internal: true
      x-accepts: application/json
  /api/v3/products/{product}/reviews/{review}:
    get:
      operationId: getProductReview
      security:
      - PersonalAccessToken:
        - product-reviews:read
      summary: Show the specified review for a product
      tags:
      - Product Reviews
      x-internal: true
      x-accepts: application/json
  /api/v3/products/{product}/versions:
    get:
      operationId: listProductVersions
      security:
      - PersonalAccessToken:
        - product-versions:read
      summary: List all versions for a product
      tags:
      - Product Versions
      x-internal: true
      x-accepts: application/json
    post:
      operationId: createProductVersion
      security:
      - PersonalAccessToken:
        - product-versions:write
      summary: Create a version for a product
      tags:
      - Product Versions
      x-internal: true
      x-contentType: multipart/form-data
      x-accepts: application/json
  /api/v3/products/{product}/versions/{version}:
    delete:
      operationId: deleteProductVersion
      security:
      - PersonalAccessToken:
        - product-versions:write
      summary: Delete the specified version for a product
      tags:
      - Product Versions
      x-internal: true
      x-accepts: application/json
    get:
      operationId: getProductVersion
      security:
      - PersonalAccessToken:
        - product-versions:read
      summary: Show the specified version for a product
      tags:
      - Product Versions
      x-internal: true
      x-accepts: application/json
    put:
      operationId: updateProductVersion
      security:
      - PersonalAccessToken:
        - product-versions:write
      summary: Update the specified version for a product
      tags:
      - Product Versions
      x-internal: true
      x-contentType: application/json
      x-accepts: application/json
  /api/v3/products/{product}/versions/{version}/download:
    post:
      operationId: getProductDownloadToken
      security:
      - PersonalAccessToken:
        - product-versions:download
      summary: Get a one time use url for downloading a product
      tags:
      - Product Versions
      x-internal: true
      x-accepts: application/json
  /api/v3/teams/{team}/products:
    get:
      operationId: listProducts
      security:
      - PersonalAccessToken:
        - products:read
      summary: List all products for a team
      tags:
      - Products
      x-internal: true
      x-accepts: application/json
  /api/v3/products/{product}:
    get:
      operationId: getProduct
      security:
      - PersonalAccessToken:
        - products:read
      summary: Get the specified product
      tags:
      - Products
      x-internal: true
      x-accepts: application/json
    put:
      operationId: updateProduct
      security:
      - PersonalAccessToken:
        - products:write
      summary: Update the specified product
      tags:
      - Products
      x-internal: true
      x-accepts: application/json
  /api/v3/users/batch:
    get:
      operationId: getUsers
      security:
      - PersonalAccessToken:
        - users:read
      summary: Fetch a batch of users by id
      tags:
      - Users
      x-internal: true
      x-accepts: application/json
  /api/v3/users:
    get:
      operationId: listUsers
      security:
      - PersonalAccessToken:
        - users:read
      summary: List all users
      tags:
      - Users
      x-internal: true
      x-accepts: application/json
  /api/v3/users/{user}:
    get:
      operationId: getUser
      security:
      - PersonalAccessToken:
        - users:read
      summary: Fetch the specified user
      tags:
      - Users
      x-internal: true
      x-accepts: application/json
  /api/v3/users/{user}/teams:
    get:
      operationId: listUserTeams
      security:
      - PersonalAccessToken:
        - teams:read
      summary: List all the specified user's teams
      tags:
      - User Teams
      x-internal: true
      x-accepts: application/json
  /api/v3/users/{user}/products:
    get:
      operationId: listUserProducts
      security:
      - PersonalAccessToken:
        - products:read
      summary: List all the specified user's products
      tags:
      - User Products
      x-internal: true
      x-accepts: application/json
  /api/v3/users/{user}/badges:
    get:
      operationId: listUserBadges
      security:
      - PersonalAccessToken:
        - user-badges:read
      summary: List all the specified user's badges
      tags:
      - User Badges
      x-internal: true
      x-accepts: application/json
    post:
      operationId: createUserBadge
      security:
      - PersonalAccessToken:
        - user-badges:write
      summary: Attach a badge to a user
      tags:
      - User Badges
      x-internal: true
      x-contentType: application/json
      x-accepts: application/json
  /api/v3/users/{user}/badges/{badge}:
    delete:
      operationId: deleteUserBadge
      security:
      - PersonalAccessToken:
        - user-badges:write
      summary: Detach a badge from a user
      tags:
      - User Badges
      x-internal: true
      x-accepts: application/json
  /api/v3/users/{user}/bans:
    get:
      operationId: listUserBans
      security:
      - PersonalAccessToken:
        - user-bans:read
      summary: List all the specified user's bans
      tags:
      - User Bans
      x-internal: true
      x-accepts: application/json
  /api/v3/users/{user}/purchases:
    get:
      operationId: listUserPurchases
      security:
      - PersonalAccessToken:
        - user-purchases:read
      summary: List all the specified user's purchases
      tags:
      - User Product Purchases
      x-internal: true
      x-accepts: application/json
components:
  securitySchemes:
    PersonalAccessToken:
      scheme: bearer
      type: http
x-tagGroups:
- name: Permission Groups
  tags:
  - Permission Groups
- name: Personal Access Tokens
  tags:
  - Personal Access Tokens
- name: Products
  tags:
  - Products
  - Product Coupons
  - Product Purchases
  - Product Reviews
  - Product Versions
- name: Teams
  tags:
  - Teams
  - Team Users
- name: Users
  tags:
  - Users
  - User Product Purchases
  - User Products
  - User Badges
  - User Bans
  - User Teams

